import React from "react";
import "./globals.css";

const TITLE = "Trustip · Protected Checkout";
const DESCRIPTION =
  "Checkout terlindungi untuk belanja di social commerce. Dana kamu ditahan aman dan baru diteruskan ke penjual setelah pesanan diterima.";

// Absolute base for og:image / twitter:image URLs. Reuses the existing
// NEXT_PUBLIC_APP_URL (set to the deployed origin in production); localhost is
// the dev fallback.
const SITE_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";

export const metadata = {
  metadataBase: new URL(SITE_URL),
  // No internal version number in a buyer's browser tab. The description is
  // what a link preview shows a BUYER when a checkout link is shared in chat,
  // so it follows the buyer language rules: Indonesian, no protocol terms.
  title: TITLE,
  description: DESCRIPTION,
  // Link previews (WhatsApp/Telegram/Twitter) when a checkout link is shared.
  // The card image is generated by app/opengraph-image.tsx and auto-injected.
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    siteName: "Trustip",
    locale: "id_ID",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

// Mobile browser chrome (address bar / task switcher) matches the VOID ground
// instead of defaulting to white around a black page.
export const viewport = {
  themeColor: "#050505",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  );
}
